// ===== Toyota Đồng Tháp — Dữ liệu chi tiết xe (giới thiệu, thông số, ưu điểm, phiên bản, giá, màu sắc) =====
// Nguồn: toyotadongthap.vn (đại lý chính hãng), tổng hợp tham khảo 07/2026.

const COLOR_HEX = {
  "Trắng": "#f5f5f5",
  "Trắng Ngọc Trai": "#f7f4ef",
  "Bạc": "#c8ccd0",
  "Xám": "#8a8d91",
  "Xám ánh kim": "#75787b",
  "Xám ánh bạc": "#a9acb0",
  "Đen": "#1c1c1c",
  "Đỏ": "#b3121b",
  "Cam": "#e07a1d",
  "Be": "#dcd2b8",
  "Vàng Cát": "#d8c07a",
  "Xanh Dương": "#1f4e8c",
  "Xanh ánh đen": "#20242b",
  "Nâu Đồng": "#6b4a33",
};

const MODELS = {
  "wigo": {
    name: "Toyota Wigo",
    category: "Hatchback hạng A",
    hero: "images/cars/wigo.jpg",
    intro:
      "Toyota Wigo là mẫu hatchback hạng A phổ biến bậc nhất tại Việt Nam nhờ giá cạnh tranh, thiết kế trẻ trung và khả năng tiết kiệm nhiên liệu vượt trội. Xe phù hợp cho người mua xe lần đầu, gia đình nhỏ và tài xế công nghệ cần một chiếc xe đô thị dễ sử dụng, tiết kiệm chi phí vận hành.",
    specs: [
      { label: "Động cơ", value: "1.2L, 3 xi-lanh" },
      { label: "Công suất", value: "87 mã lực" },
      { label: "Mô-men xoắn", value: "108 Nm" },
      { label: "Hộp số", value: "5MT / CVT" },
      { label: "Dẫn động", value: "FWD (cầu trước)" },
      { label: "Số chỗ ngồi", value: "5" },
      { label: "Phân khúc", value: "Hatchback hạng A" },
      { label: "Tiêu hao nhiên liệu", value: "4,3 – 5,0 L/100km" },
    ],
    features: [
      "Đèn pha LED projector với dải đèn định vị ban ngày hình chữ L",
      "Lưới tản nhiệt cỡ lớn thể thao, cản trước tạo hình khỏe khoắn",
      "Mâm hợp kim 14 inch hai tông màu, gương chỉnh/gập điện tích hợp xi-nhan",
      "Màn hình cảm ứng 7-8 inch hỗ trợ Apple CarPlay & Android Auto",
      "Vô lăng thể thao 3 chấu, khởi động nút bấm (bản G)",
      "An toàn tiêu chuẩn ABS/EBD/BA, cân bằng điện tử ESP, hỗ trợ khởi hành ngang dốc HAC",
      "Chốt ISOFIX cho ghế trẻ em trên toàn bộ phiên bản",
      "Camera lùi và cảm biến hỗ trợ đỗ xe (bản G)",
    ],
    trims: [
      { name: "Wigo 1.0 5MT (Số sàn)", price: 360000000 },
      { name: "Wigo 1.0 4AT (Số tự động)", price: 405000000 },
    ],
    colors: ["Trắng", "Đỏ", "Cam", "Bạc", "Xám", "Đen"],
    note: "",
  },
  "vios": {
    name: "Toyota Vios",
    category: "Sedan hạng B",
    hero: "images/cars/vios.webp",
    intro:
      "Toyota Vios là mẫu sedan hạng B bán chạy nhất Việt Nam, nổi bật với độ bền, giá trị bán lại cao và chi phí vận hành tiết kiệm. Khoang hành lý 506 lít cùng thiết kế thực dụng phù hợp cho gia đình đô thị và các đơn vị kinh doanh vận tải, taxi công nghệ.",
    specs: [
      { label: "Động cơ", value: "1.5L 2NR-FE, Dual VVT-i" },
      { label: "Công suất", value: "106 mã lực @ 6.000 vòng/phút" },
      { label: "Mô-men xoắn", value: "140 – 145 Nm" },
      { label: "Hộp số", value: "5MT / CVT" },
      { label: "Dẫn động", value: "FWD (cầu trước)" },
      { label: "Số chỗ ngồi", value: "5" },
      { label: "Phân khúc", value: "Sedan hạng B" },
      { label: "Tiêu hao nhiên liệu", value: "~5,77 – 6,02 L/100km" },
    ],
    features: [
      "Đèn pha và đèn hậu LED phía trước/sau, tiết kiệm điện và tăng khả năng nhận diện",
      "Mâm hợp kim hai tông màu 15 inch, gương gập điện tích hợp xi-nhan",
      "Bản G CVT: tay nắm cửa mạ chrome, chìa khóa thông minh, khởi động nút bấm",
      "Ghế da, vô lăng bọc da, đèn nội thất ambient (bản G)",
      "Màn hình giải trí cảm ứng hỗ trợ Bluetooth/USB",
      "An toàn tiêu chuẩn ABS/EBD/BA/VSC/HAC, camera lùi và cảm biến đỗ xe",
      "Bản G CVT: 7 túi khí và gói an toàn Toyota Safety Sense (cảnh báo tiền va chạm, cảnh báo lệch làn)",
    ],
    trims: [
      { name: "Vios 1.5E MT (Số sàn)", price: 458000000 },
      { name: "Vios 1.5E CVT", price: 488000000 },
      { name: "Vios 1.5G CVT", price: 545000000 },
    ],
    colors: ["Trắng", "Bạc", "Xám", "Đen", "Đỏ", "Be"],
    note: "",
  },
  "veloz-cross": {
    name: "Toyota Veloz Cross",
    category: "MPV gia đình",
    hero: "images/cars/veloz-cross.webp",
    intro:
      "Toyota Veloz Cross là mẫu MPV 7 chỗ hoàn toàn mới, kết hợp thiết kế năng động kiểu crossover với không gian rộng rãi, linh hoạt cho gia đình. Xe sử dụng động cơ xăng 1.5L, hộp số CVT êm ái, phù hợp cho các gia đình nhiều thành viên cần một chiếc xe đa dụng, tiết kiệm nhiên liệu.",
    specs: [
      { label: "Động cơ", value: "1.5L 2NR-VE, Dual VVT-i" },
      { label: "Công suất", value: "105 mã lực @ 6.000 vòng/phút" },
      { label: "Mô-men xoắn", value: "138 Nm @ 4.200 vòng/phút" },
      { label: "Hộp số", value: "CVT" },
      { label: "Dẫn động", value: "FWD (cầu trước)" },
      { label: "Số chỗ ngồi", value: "7" },
      { label: "Phân khúc", value: "MPV gia đình" },
    ],
    features: [
      "Đèn pha LED tầng, tự động bật/tắt, đèn pha thích ứng thông minh",
      "Mâm hợp kim 17 inch phay xước hai tông màu (bản Top)",
      "Camera quan sát toàn cảnh 360 độ, cảnh báo điểm mù",
      "Đồng hồ kỹ thuật số 7 inch, giao diện tùy chỉnh thông minh",
      "Màn hình giải trí nổi 9 inch, hỗ trợ Apple CarPlay & Android Auto",
      "6 túi khí, ABS, EBD, cân bằng điện tử VSC",
      "Phanh đĩa trên cả 4 bánh xe",
    ],
    trims: [
      { name: "Veloz Cross CVT", price: 638000000 },
      { name: "Veloz Cross CVT Top", price: 660000000 },
    ],
    colors: ["Trắng Ngọc Trai", "Bạc", "Đen", "Đỏ", "Xám"],
    note: "Màu Trắng Ngọc Trai phụ thu thêm 8.000.000₫.",
  },
  "avanza-premio": {
    name: "Toyota Avanza Premio",
    category: "MPV 7 chỗ",
    hero: "images/cars/avanza-premio.jpg",
    intro:
      "Toyota Avanza Premio là mẫu MPV 7 chỗ cỡ nhỏ được nâng cấp toàn diện về thiết kế, trang bị và vận hành, giá cả dễ tiếp cận. Xe phù hợp cho các gia đình trẻ hoặc tài xế dịch vụ/công nghệ cần không gian rộng rãi, tiết kiệm nhiên liệu.",
    specs: [
      { label: "Động cơ", value: "1.5L DOHC, Dual VVT-i" },
      { label: "Công suất", value: "105 mã lực @ 6.000 vòng/phút" },
      { label: "Mô-men xoắn", value: "138 Nm @ 4.200 vòng/phút" },
      { label: "Hộp số", value: "5MT / CVT" },
      { label: "Dẫn động", value: "FWD (cầu trước)" },
      { label: "Số chỗ ngồi", value: "7 (bố trí 2-3-2)" },
      { label: "Phân khúc", value: "MPV cỡ nhỏ" },
      { label: "Tiêu hao nhiên liệu", value: "~6,3 L/100km (đô thị)" },
    ],
    features: [
      "Lưới tản nhiệt tổ ong cỡ lớn, đèn pha LED sắc nét, góc cạnh hơn",
      "Mâm hợp kim 16 inch (bản CVT) / 15 inch (bản MT), gương gập điện tích hợp xi-nhan",
      "Màn hình cảm ứng 8 inch hỗ trợ Apple CarPlay",
      "2 giàn lạnh (trước + sau), vô lăng 3 chấu tích hợp nút điều khiển",
      "Khoang cabin 7 chỗ rộng rãi, bố trí 2-3-2 thoải mái",
      "An toàn: ABS, EBD/BA, cân bằng điện tử VSC, 2 túi khí trước",
      "Camera lùi và cảm biến sau (bản CVT)",
    ],
    trims: [
      { name: "Avanza Premio MT (Số sàn)", price: 548000000 },
      { name: "Avanza Premio CVT", price: 598000000 },
    ],
    colors: ["Trắng", "Bạc", "Đen", "Đỏ", "Xám"],
    note: "",
  },
  "yaris-cross": {
    name: "Toyota Yaris Cross",
    category: "SUV hạng B",
    hero: "images/cars/yaris-cross.webp",
    intro:
      "Toyota Yaris Cross là mẫu SUV đô thị hạng B hoàn toàn mới, thiết kế năng động, trang bị hiện đại và công nghệ an toàn tiên tiến, nổi bật với phiên bản Hybrid tiết kiệm nhiên liệu. Phù hợp cho người trẻ và gia đình trẻ cần một chiếc xe linh hoạt cho cả đô thị lẫn đường dài.",
    specs: [
      { label: "Động cơ", value: "1.5L xăng (2NR-VE) / 1.5L Hybrid" },
      { label: "Công suất", value: "105 mã lực (xăng) / 90 mã lực kết hợp (Hybrid)" },
      { label: "Hộp số", value: "CVT (xăng) / e-CVT (Hybrid)" },
      { label: "Dẫn động", value: "FWD (cầu trước)" },
      { label: "Số chỗ ngồi", value: "5" },
      { label: "Phân khúc", value: "SUV đô thị hạng B" },
      { label: "Màn hình", value: "10,1 inch (cả 2 phiên bản)" },
    ],
    features: [
      "Lưới tản nhiệt tổ ong hình thang, cụm đèn LED 3D phía trước/sau",
      "Mâm hợp kim hai tông màu 18 inch, cửa sổ trời toàn cảnh",
      "Ghế lái chỉnh điện 8 hướng, vô lăng bọc da 3 chấu, đồng hồ kỹ thuật số TFT 7 inch",
      "Đèn nội thất ambient 64 màu, sạc không dây Qi, dàn âm thanh JBL 8 loa (bản HEV)",
      "Nền tảng khung gầm mới DNGA-B, khoảng sáng gầm xe 210mm",
      "Gói an toàn Toyota Safety Sense: cảnh báo tiền va chạm, giữ làn đường, kiểm soát hành trình thích ứng, cảnh báo điểm mù",
      "Camera 360 độ và cảm biến hỗ trợ đỗ xe",
    ],
    trims: [
      { name: "Yaris Cross 1.5G (Xăng)", price: 650000000 },
      { name: "Yaris Cross 1.5 HEV (Hybrid)", price: 765000000 },
    ],
    colors: ["Trắng", "Đen", "Đỏ", "Vàng Cát", "Bạc", "Xanh Dương"],
    note: "",
  },
  "corolla-altis": {
    name: "Toyota Corolla Altis",
    category: "Sedan hạng C",
    hero: "images/cars/corolla-altis.jpg",
    intro:
      "Toyota Corolla Altis là mẫu sedan hạng C nhập khẩu Thái Lan, gồm 2 phiên bản xăng (1.8G, 1.8V) và 1 phiên bản Hybrid (1.8HEV). Bản nâng cấp nhẹ với thiết kế đầu/thân xe mới, phù hợp cho khách hàng cần sự cân bằng giữa tiết kiệm nhiên liệu và vận hành, trong đó Hybrid là phiên bản công nghệ cao cấp nhất.",
    specs: [
      { label: "Động cơ", value: "1.8L 2ZR-FBE (xăng hoặc hybrid)" },
      { label: "Công suất", value: "122 – 138 mã lực" },
      { label: "Mô-men xoắn", value: "142 – 172 Nm" },
      { label: "Hộp số", value: "CVT (có lẫy chuyển số ở một số bản)" },
      { label: "Dẫn động", value: "FWD (cầu trước)" },
      { label: "Số chỗ ngồi", value: "5" },
      { label: "Phân khúc", value: "Sedan hạng C" },
      { label: "Tiêu hao nhiên liệu", value: "4,5 – 6,8 L/100km" },
    ],
    features: [
      "Lưới tản nhiệt tổ ong mới, đèn pha Bi-LED tự động bật/tắt",
      "Bảng đồng hồ kỹ thuật số 12,3 inch trên toàn bộ phiên bản",
      "Màn hình cảm ứng 9 inch kết nối không dây với điện thoại",
      "Ghế lái chỉnh điện 10 hướng bọc da, vô lăng bọc da 3 chấu",
      "Điều hòa tự động 2 vùng độc lập, vận hành êm ái",
      "Bản Hybrid (1.8HEV): chế độ lái EV/Eco/Normal/Sport, camera 360 độ",
      "Cảnh báo điểm mù và cảnh báo phương tiện cắt ngang phía sau (bản 1.8V trở lên)",
      "Bảo hành pin Hybrid 7 năm/150.000km (bản 1.8HEV)",
    ],
    trims: [
      { name: "Corolla Altis 1.8G", price: 725000000 },
      { name: "Corolla Altis 1.8V", price: 780000000 },
      { name: "Corolla Altis 1.8 HEV (Hybrid)", price: 870000000 },
    ],
    colors: ["Xám", "Đỏ", "Trắng Ngọc Trai", "Đen", "Bạc"],
    colorPhotos: {
      "Xám": "images/colors/altis-xam.jpg",
      "Đỏ": "images/colors/altis-do.jpg",
      "Trắng Ngọc Trai": "images/colors/altis-trang-ngoc-trai.jpg",
      "Đen": "images/colors/altis-den.jpg",
    },
    note: "",
  },
  "corolla-cross": {
    name: "Toyota Corolla Cross",
    category: "SUV/CUV hạng C",
    hero: "images/cars/corolla-cross.webp",
    intro:
      "Toyota Corolla Cross là thế hệ SUV đô thị mới nhất của Toyota, hướng đến khách hàng gia đình và cá nhân yêu thích sự an toàn, thoải mái và tiết kiệm nhiên liệu, đặc biệt phù hợp với điều kiện giao thông đô thị tại Việt Nam.",
    specs: [
      { label: "Động cơ", value: "1.8L xăng (G, V) / 1.8L Hybrid (HEV)" },
      { label: "Công suất", value: "140 mã lực (xăng) / 121 mã lực kết hợp (HEV)" },
      { label: "Hộp số", value: "CVT (tất cả phiên bản)" },
      { label: "Dẫn động", value: "FWD (cầu trước)" },
      { label: "Số chỗ ngồi", value: "5" },
      { label: "Phân khúc", value: "SUV đô thị hạng B+" },
      { label: "Khoang hành lý", value: "487 lít" },
      { label: "Khoảng sáng gầm xe", value: "161 mm" },
    ],
    features: [
      "Lưới tản nhiệt tổ ong lớn, đèn pha Full LED, dải đèn hậu LED liền mạch viền chrome",
      "Mâm hợp kim 17-18 inch, thanh giá nóc thể thao, ốp cản trước/sau nhựa đen",
      "Ghế da cao cấp, chỉnh điện 8 hướng cho ghế lái, cửa sổ trời toàn cảnh (bản HEV)",
      "Điều hòa tự động 2 vùng độc lập, màn hình 9 inch, đồng hồ kỹ thuật số 7 inch (V/HEV)",
      "Cổng sạc USB và sạc không dây, khoang hành lý 487L với ghế gập tỉ lệ 60:40",
      "Nền tảng khung gầm toàn cầu TNGA-C, hệ thống treo độc lập êm ái",
      "Gói an toàn Toyota Safety Sense đầy đủ (cảnh báo tiền va chạm, giữ làn, kiểm soát hành trình thích ứng), 7 túi khí, khung GOA hấp thụ va chạm",
    ],
    trims: [
      { name: "Corolla Cross 1.8G", price: 765000000 },
      { name: "Corolla Cross 1.8V", price: 860000000 },
      { name: "Corolla Cross 1.8 HEV (Hybrid)", price: 955000000 },
    ],
    colors: [],
    note: "",
  },
  "camry": {
    name: "Toyota Camry",
    category: "Sedan hạng D",
    hero: "images/cars/camry.jpg",
    intro:
      "Toyota Camry là mẫu sedan hạng D cao cấp thế hệ mới, có cả phiên bản xăng và Hybrid, giữ nguyên tỷ lệ thân xe sedan truyền thống. Xe hướng đến khách hàng cần sự thoải mái kết hợp công nghệ tiên tiến, trong đó bản Hybrid là lựa chọn hiệu năng và công nghệ cao hơn.",
    specs: [
      { label: "Động cơ", value: "2.0L xăng / 2.5L Hybrid (HEV)" },
      { label: "Công suất", value: "170 mã lực (xăng) / 231 mã lực kết hợp (Hybrid)" },
      { label: "Mô-men xoắn (HEV)", value: "221 Nm" },
      { label: "Hộp số", value: "8AT (2.0Q) / e-CVT (Hybrid)" },
      { label: "Dẫn động", value: "FWD (cầu trước)" },
      { label: "Số chỗ ngồi", value: "5" },
      { label: "Phân khúc", value: "Sedan hạng D cao cấp" },
      { label: "Khoảng sáng gầm xe", value: "135 mm" },
    ],
    features: [
      "Thiết kế đầu xe mới theo phong cách \"đầu cá mập\"",
      "Hệ thống Hybrid thế hệ thứ 5 với pin lithium-ion (bản HEV)",
      "Gói an toàn Toyota Safety Sense 3.0 đầy đủ",
      "Bảng đồng hồ kỹ thuật số và màn hình giải trí 12,3 inch",
      "Sạc điện thoại không dây và kết nối thông minh",
      "7 túi khí tiêu chuẩn trên toàn bộ phiên bản",
    ],
    trims: [
      { name: "Camry 2.0Q", price: 1220000000 },
      { name: "Camry HEV MID (Hybrid)", price: 1460000000 },
      { name: "Camry HEV TOP (Hybrid)", price: 1530000000 },
    ],
    colors: ["Xám ánh kim", "Xám ánh bạc", "Trắng Ngọc Trai", "Đỏ", "Đen"],
    colorPhotos: {
      "Xám ánh kim": "images/colors/camry-xam-anh-kim.png",
      "Xám ánh bạc": "images/colors/camry-xam-anh-bac.png",
      "Trắng Ngọc Trai": "images/colors/camry-trang-ngoc-trai.png",
      "Đỏ": "images/colors/camry-do.png",
      "Đen": "images/colors/camry-den.png",
    },
    note: "",
  },
  "innova-cross": {
    name: "Toyota Innova Cross",
    category: "MPV cao cấp",
    hero: "images/cars/innova-cross.webp",
    intro:
      "Toyota Innova Cross là mẫu MPV lai SUV thế hệ mới, nhập khẩu từ Indonesia, mang dáng vẻ thể thao của SUV kết hợp không gian rộng rãi của MPV. Xe có phiên bản 8 chỗ (xăng) hoặc 7 chỗ (Hybrid), phù hợp cho gia đình đông thành viên và dịch vụ vận chuyển cao cấp.",
    specs: [
      { label: "Động cơ", value: "2.0L Dynamic Force (xăng) / 2.0L Hybrid" },
      { label: "Công suất", value: "~172–174 mã lực (xăng) / 184 mã lực kết hợp (Hybrid)" },
      { label: "Hộp số", value: "CVT (xăng) / e-CVT (Hybrid)" },
      { label: "Dẫn động", value: "FWD (cầu trước)" },
      { label: "Số chỗ ngồi", value: "8 (xăng) / 7 (Hybrid)" },
      { label: "Phân khúc", value: "MPV cao cấp" },
      { label: "Khoảng sáng gầm xe", value: "185 mm" },
      { label: "Màn hình", value: "10,1 inch" },
    ],
    features: [
      "Lưới tản nhiệt lục giác lớn viền chrome, đèn pha LED tích hợp DRL",
      "Thân xe cơ bắp, cản trước vuông vức chắc chắn",
      "Mâm hợp kim 17-18 inch, ghế da hai tông màu nâu-đen",
      "Ghế lái chỉnh điện 8 hướng, hàng ghế sau độc lập kiểu \"thương gia\" (bản Hybrid)",
      "Camera 360 độ, điều hòa tự động 2 vùng, cửa sổ trời toàn cảnh, cốp điện (bản Hybrid)",
      "6 túi khí, ABS/EBD/BA/VSC/HAC, phanh tay điện tử tự giữ",
      "Bản Hybrid: gói Toyota Safety Sense 3.0 gồm cảnh báo tiền va chạm, cảnh báo lệch làn, kiểm soát hành trình thích ứng, cảnh báo điểm mù và phương tiện cắt ngang",
    ],
    trims: [
      { name: "Innova Cross 2.0 Xăng", price: 825000000 },
      { name: "Innova Cross 2.0 HEV (Hybrid)", price: 1005000000 },
    ],
    colors: ["Trắng Ngọc Trai", "Bạc", "Đen", "Nâu Đồng", "Xanh ánh đen"],
    note: "Màu Trắng Ngọc Trai phụ thu thêm 8.000.000₫.",
  },
  "fortuner": {
    name: "Toyota Fortuner",
    category: "SUV 7 chỗ",
    hero: "images/cars/fortuner.jpg",
    intro:
      "Toyota Fortuner là mẫu SUV khung gầm rời nổi tiếng, phiên bản nâng cấp với thiết kế trẻ trung hơn, khoang lái thể thao và bổ sung công nghệ an toàn. Bản Legender hướng đến khách hàng trẻ tuổi với ngoại hình thể thao hơn. Xe có 7 phiên bản gồm máy dầu (lắp ráp trong nước) và máy xăng (nhập khẩu Indonesia), cấu hình 4x2 và 4x4.",
    specs: [
      { label: "Động cơ", value: "2.4L / 2.7L / 2.8L (Diesel và xăng)" },
      { label: "Công suất (2.8L)", value: "201 mã lực @ 3.400 vòng/phút" },
      { label: "Mô-men xoắn (2.8L)", value: "500 Nm @ 1.600 vòng/phút" },
      { label: "Hộp số", value: "Tự động 6 cấp" },
      { label: "Dẫn động", value: "4x2 / 4x4 (khóa vi sai điện tử trên 4x4)" },
      { label: "Số chỗ ngồi", value: "7" },
      { label: "Phân khúc", value: "SUV khung gầm rời cỡ trung" },
      { label: "Khoảng sáng gầm xe", value: "~219 mm" },
    ],
    features: [
      "Lưới tản nhiệt bản lớn, đèn pha LED tông lạnh, mâm 18 inch hai tông đen-bạc (Legender)",
      "Đèn hậu LED hiện đại, gương chỉnh/gập điện tích hợp đèn xi-nhan",
      "Khoang lái hai tông đen-đỏ (Legender), ghế lái chỉnh điện 8 hướng",
      "Khởi động nút bấm, màn hình cảm ứng 8 inch, dàn âm thanh JBL 11 loa",
      "Hệ thống treo tay đòn kép trước / đa liên kết sau, khóa vi sai hỗ trợ off-road",
      "Cảnh báo tiền va chạm kèm hỗ trợ phanh, cảnh báo lệch làn/điểm mù, kiểm soát hành trình thích ứng",
      "Khung gầm gia cường với vùng hấp thụ va chạm trước/sau, kiểm soát lực kéo A-TRC",
    ],
    trims: [
      { name: "Fortuner 2.4 AT 4x2", price: 1118000000 },
      { name: "Fortuner 2.7 AT 4x2", price: 1229000000 },
      { name: "Fortuner Legender 2.4 AT 4x2", price: 1259000000 },
      { name: "Fortuner 2.7 AT 4x4", price: 1319000000 },
      { name: "Fortuner 2.8 AT 4x4", price: 1434000000 },
      { name: "Fortuner Legender 2.8 AT 4x4", price: 1470000000 },
    ],
    colors: [],
    note: "",
  },
  "hilux": {
    name: "Toyota Hilux",
    category: "Bán tải đa dụng",
    hero: "images/cars/hilux.webp",
    intro:
      "Toyota Hilux là mẫu bán tải với ngoại hình được thiết kế lại hoàn toàn, nhập khẩu từ Thái Lan, cấu hình 5 chỗ ngồi qua 3 phiên bản. Xe phù hợp cho khách hàng cần một chiếc bán tải đa dụng vừa chở hàng vừa di chuyển gia đình, có khả năng off-road tốt.",
    specs: [
      { label: "Động cơ", value: "2.4L Diesel / 2.8L Diesel (Adventure)" },
      { label: "Hộp số", value: "6MT (2.4 4x4) / 6AT (2.4 4x2, 2.8 Adventure)" },
      { label: "Dẫn động", value: "4x2 / 4x4" },
      { label: "Số chỗ ngồi", value: "5" },
      { label: "Phân khúc", value: "Bán tải (Pickup)" },
      { label: "Màn hình", value: "9 inch (bản Adventure)" },
    ],
    features: [
      "Lưới tản nhiệt hình thang dạng tổ ong lớn, đèn sương mù Bi-LED",
      "Đường gân dập nổi thân xe, cụm đèn hậu LED hình chữ U, mâm hợp kim 18 inch",
      "Màn hình giải trí 9 inch, 6 loa hỗ trợ Apple CarPlay/Android Auto",
      "Hộc chứa đồ làm mát bằng hơi lạnh điều hòa, cửa gió điều hòa hàng ghế sau riêng biệt",
      "Động cơ dầu tăng áp phun trực tiếp, khung gầm rời gia cường chắc chắn",
      "Hỗ trợ khởi hành ngang dốc (HAC) và kiểm soát lực kéo (TRC) từng bánh",
      "Cân bằng điện tử VSC, túi khí trước/bên/rèm/đầu gối, dây an toàn 3 điểm cho mọi hàng ghế, chốt ISOFIX",
      "Cảnh báo điểm mù (BSM) kèm cảnh báo phương tiện cắt ngang phía sau",
    ],
    trims: [
      { name: "Hilux 2.4L 4x4 MT", price: 668000000 },
      { name: "Hilux 2.4L 4x2 AT", price: 706000000 },
      { name: "Hilux 2.8L 4x4 AT Adventure", price: 999000000 },
    ],
    colors: ["Trắng Ngọc Trai", "Bạc", "Xám", "Đen", "Đỏ", "Xanh Dương"],
    note: "",
  },
  "raize": {
    name: "Toyota Raize",
    category: "SUV/CUV đô thị 5 chỗ",
    hero: "images/cars/raize.jpg",
    intro:
      "Toyota Raize là mẫu SUV đô thị hạng A theo phong cách thời trang, trẻ trung, nhập khẩu từ Indonesia. Xe chỉ có động cơ xăng tăng áp, cấu hình 5 chỗ, hướng đến khách hàng trẻ hoặc đô thị muốn sở hữu một chiếc SUV cỡ nhỏ có cá tính riêng.",
    specs: [
      { label: "Động cơ", value: "1.0L Turbo, 3 xi-lanh" },
      { label: "Công suất", value: "98 mã lực @ 6.000 vòng/phút" },
      { label: "Mô-men xoắn", value: "140 Nm (2.400–4.000 vòng/phút)" },
      { label: "Hộp số", value: "D-CVT" },
      { label: "Số chỗ ngồi", value: "5" },
      { label: "Phân khúc", value: "SUV/CUV đô thị hạng A" },
      { label: "Khoang hành lý", value: "369 lít (có thể mở rộng)" },
      { label: "Màn hình", value: "9 inch, hỗ trợ Apple CarPlay" },
    ],
    features: [
      "Thiết kế ngoại thất thời trang, cá tính, khác biệt trong phân khúc",
      "Mâm 17 inch họa tiết cánh quạt, cụm đèn Full LED trước/sau",
      "Ốp cản nhựa đen thể thao, tạo cảm giác chắc chắn",
      "Bảng đồng hồ kỹ thuật số với 4 chế độ hiển thị (Advanced, Exciting, Simple, Analog)",
      "Vô lăng đa chức năng 3 chấu tích hợp điều khiển âm thanh/cuộc gọi",
      "Động cơ tăng áp 1.0L 3 xi-lanh kết hợp hộp số D-CVT vận hành êm ái",
      "Hệ thống treo được tinh chỉnh êm dịu, ổn định khi vận hành",
    ],
    trims: [
      { name: "Raize 1 Tone màu", price: 510000000 },
      { name: "Raize 2 Tone màu", price: 518000000 },
      { name: "Raize Trắng Ngọc Trai", price: 518000000 },
    ],
    colors: [],
    note: "Màu sắc gắn theo phiên bản 1 Tone / 2 Tone / Trắng Ngọc Trai.",
  },
};
